{{if .UseMakefile -}}
.PHONY: run build test tidy {{if .UseDocker}}docker-up docker-down{{end}}

run:
	go run ./cmd/server

build:
	go build -o bin/server ./cmd/server

test:
	go test ./...

tidy:
	go mod tidy
{{- if .UseDocker}}

docker-up:
	docker compose up -d

docker-down:
	docker compose down
{{- end}}
{{- end}}
